on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        platform: [ubuntu-latest]
    name: Run ${{ matrix.go-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -v ./...
